export enum RoutePaths {
  all = '*',
  root = '/',
  auth = '/authorization',
  events = '/events',
  users = '/users',
  roles = '/roles',
  groups = '/groups',
  tc = '/tc',
  alkozamki = '/alkozamki',
  attachments = '/attachments',
  autoService = '/auto_service',
  historyAutoService = '/historyAutoService',
  changePassword = '/changePassword',
  forgetPassword = '/forgetPassword',
  resetPassword = '/resetPassword',
}
